//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AkarsuOtel.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OtelDBEntities : DbContext
    {
        public OtelDBEntities()
            : base("name=OtelDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BANKA> BANKA { get; set; }
        public virtual DbSet<BANKAHAREKET> BANKAHAREKET { get; set; }
        public virtual DbSet<BIRIM> BIRIM { get; set; }
        public virtual DbSet<CARI> CARI { get; set; }
        public virtual DbSet<CARIHAREKET> CARIHAREKET { get; set; }
        public virtual DbSet<CARIKONUKHAREKET> CARIKONUKHAREKET { get; set; }
        public virtual DbSet<CARITUR> CARITUR { get; set; }
        public virtual DbSet<DEPARTMAN> DEPARTMAN { get; set; }
        public virtual DbSet<GOREV> GOREV { get; set; }
        public virtual DbSet<ISLEM> ISLEM { get; set; }
        public virtual DbSet<KASA> KASA { get; set; }
        public virtual DbSet<KASAHAREKET> KASAHAREKET { get; set; }
        public virtual DbSet<KURLAR> KURLAR { get; set; }
        public virtual DbSet<ODALAR> ODALAR { get; set; }
        public virtual DbSet<PERSONEL> PERSONEL { get; set; }
        public virtual DbSet<REZERVASYON> REZERVASYON { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<TBLDURUM> TBLDURUM { get; set; }
        public virtual DbSet<TELEFON> TELEFON { get; set; }
        public virtual DbSet<URUN> URUN { get; set; }
        public virtual DbSet<URUNGRUP> URUNGRUP { get; set; }
        public virtual DbSet<UYRUK> UYRUK { get; set; }
    }
}
